################################################################################
# Makefile to build the SCARF3D library
################################################################################

# set dependencies if invoked with 'examples' argument
examples: fortran

# invoke MAKE with 'fortran' argument
fortran:
	cd fortran; $(MAKE)	$@

clean:
	cd fortran; $(MAKE) $@

.PHONY: fortran
