function [] = vizme(prec, fin, n, dh);

% simple script to visualize the random field generated by SCARF3D
% e.g.: viz3d('single', 'fim_struct_whole_3d', [500 500 500], 0.05);

ndim = length(n);

if ndim == 2; n = [n(1) n(2) 1]; end;

fid = fopen(fin, 'rb');
tmp = fread(fid, [prod(n)], prec);
field = reshape(tmp, [n(1) n(2) n(3)]);

x = [0:n(1)-1] * dh;
y = [0:n(2)-1] * dh;
z = [0:n(3)-1] * dh;

[X, Y, Z] = meshgrid(y, x, z);

figure;

if ndim == 3
  slice(X, Y, Z, field*100, [dh * n(1)/2], [dh * n(2)/2], [dh * n(3)/2]), shading flat, axis equal;
elseif ndim == 2
  pcolor(X, Y, squeeze(field)*100), shading flat, axis equal;
end

colorbar;

title('Random Perturbations (%)'); xlabel('Y axis'); ylabel('X axis');

if ndim == 3
  set(gca,'ZDir', 'Reverse');
  zlabel('Z axis');
end
